"""Export the rig as URDF, so the same hand can be loaded into RViz, Gazebo,
MoveIt, or any other simulator.

The URDF is generated from `robot_hand.FINGER_RIG` rather than hand-written, so
it cannot drift out of sync with the renderer: joint count, axes, link lengths
and limits all come straight from the single source of truth.

Frame convention (identical to the renderer): each finger link's local +Y runs
along the bone, local +Z is the palm normal, and flexion is rotation about
local +X. A URDF `<joint>` rotates about its axis *in the child link frame*,
so every joint here is emitted with `axis = 1 0 0`.
"""

from __future__ import annotations

import math
from xml.etree import ElementTree as ET

import numpy as np

from .math3d import mat_to_euler_zyx, vec
from .robot_hand import (
    FINGER_RIG,
    FINGERS,
    PALM_CENTER,
    PALM_HALF,
    RobotHand,
)

# Joint-name suffixes, in order, matching the rig's segment order.
JOINT_SUFFIX = ("mcp", "pip", "dip")

MATERIALS = {
    "shell": (0.42, 0.46, 0.52, 1.0),
    "bone": (0.62, 0.66, 0.72, 1.0),
    "joint": (0.10, 0.11, 0.13, 1.0),
    "accent": (0.72, 0.55, 0.24, 1.0),
}


def _f(v: float) -> str:
    # 12 significant digits: enough that a text round-trip of the rig's double
    # precision joint limits and origins is effectively lossless.
    return f"{float(v):.12g}"


def _rpy(rot: np.ndarray) -> str:
    """URDF's `rpy` attribute is ordered roll, pitch, yaw (and means
    Rz(yaw) @ Ry(pitch) @ Rx(roll)) - not the yaw-first order we use internally.
    """
    yaw, pitch, roll = mat_to_euler_zyx(np.asarray(rot, float))
    return f"{_f(roll)} {_f(pitch)} {_f(yaw)}"


def _origin_xml(parent, xyz=None, rot=None) -> ET.Element:
    el = ET.Element("origin")
    if xyz is not None:
        el.set("xyz", " ".join(_f(c) for c in np.asarray(xyz, float)))
    if rot is not None:
        el.set("rpy", _rpy(rot))
    return el


def _add_material(robot: ET.Element, name: str) -> None:
    mat = ET.SubElement(robot, "material", name=name)
    ET.SubElement(mat, "color", rgba=" ".join(_f(c) for c in MATERIALS[name]))


def build_urdf(hand: str = "Right", name: str = "robohand") -> str:
    """Return a URDF string for the rig. `hand` picks the handedness."""
    if hand not in ("Right", "Left"):
        raise ValueError(f"hand must be 'Right' or 'Left', got {hand!r}")

    robot = ET.Element("robot", name=f"{name}_{hand.lower()}")

    comment = ET.Comment(
        " Generated by robohand.urdf_export - do not edit by hand; edit\n"
        " robohand/robot_hand.py (FINGER_RIG) and re-export. "
    )
    robot.append(comment)

    for mat in MATERIALS:
        _add_material(robot, mat)

    # --- zero-pose kinematics (the pose the joint origins are expressed in) ---
    zero = RobotHand(hand)
    zero.set_pose({f"{f}_flex": 0.0 for f in FINGERS})
    zero.solve()

    sign = -1.0 if hand == "Left" else 1.0
    mirror = np.array([sign, 1.0, 1.0])
    def m_pt(p):
        return np.asarray(p, float) * mirror

    def m_rot(r):
        # Reuse the rig's own mirroring so the two paths cannot disagree.
        return zero.mirror_rotation(r)

    # --- palm ---------------------------------------------------------------
    link = ET.SubElement(robot, "link", name="base_link")
    ET.SubElement(
        link, "inertial",
    )  # placeholder replaced below with a real inertia block
    link.remove(link.find("inertial"))
    _box_visual(link, "palm", PALM_CENTER, np.eye(3), PALM_HALF, "shell")
    _box_inertial(link, "palm", PALM_CENTER, np.eye(3), PALM_HALF, 1200.0)
    _cylinder_visual(
        link, "wrist", vec(0.0, -0.080, 0.0), vec(0.0, -0.130, 0.0),
        0.027, 0.022, "shell",
    )
    _cylinder_visual(
        link, "knuckle_bar", vec(-0.027, 0.001, 0.010), vec(0.027, 0.001, 0.010),
        0.0098, 0.0098, "accent",
    )

    # --- fingers ------------------------------------------------------------
    for finger in FINGERS:
        frames = zero.chain(finger, {})
        segs = FINGER_RIG[finger][2]
        parent = "base_link"

        for i, (length, radius, max_flex) in enumerate(segs):
            suffix = JOINT_SUFFIX[i]
            link_name = f"{finger}_{suffix}_link"
            joint_name = f"{finger}_{suffix}"

            # The bone for this segment runs along the frame of the NEXT joint,
            # because the rig steps after rotating. Orienting the child link
            # from frames[i] instead would tilt every link by the splay.
            pos = m_pt(frames[i][0])
            rot = m_rot(frames[i + 1][1])

            # A URDF joint origin is expressed in the PARENT link's frame, so
            # re-express the child frame relative to the link it hangs off.
            if i == 0:
                parent_pos, parent_rot = vec(0.0, 0.0, 0.0), np.eye(3)
            else:
                parent_pos = m_pt(frames[i - 1][0])
                parent_rot = m_rot(frames[i][1])
            rel_xyz = parent_rot.T @ (pos - parent_pos)
            rel_rot = parent_rot.T @ rot

            # Child frame sits at the joint; the bone runs along its local +Y.
            link = ET.SubElement(robot, "link", name=link_name)
            _cylinder_visual(
                link, f"{finger}_{suffix}_bone",
                vec(0.0, 0.0, 0.0), vec(0.0, length, 0.0),
                radius, radius * 0.88, "bone",
            )
            _sphere_visual(link, f"{finger}_{suffix}_knuckle",
                           vec(0.0, 0.0, 0.0), radius * 1.06, "joint")
            _cylinder_inertial(
                link, f"{finger}_{suffix}_bone", length, radius, 1400.0
            )

            joint = ET.SubElement(robot, "joint", name=joint_name, type="revolute")
            ET.SubElement(joint, "parent", link=parent)
            ET.SubElement(joint, "child", link=link_name)
            joint.append(_origin_xml(None, xyz=rel_xyz, rot=rel_rot))
            # Flexion is rotation about local +X. A mirrored frame also needs a
            # negated axis (equivalently a negated angle); negating the axis
            # rather than the limits keeps "positive = more curl" for both
            # hands, so a controller can use the same sign convention.
            axis = "-1 0 0" if hand == "Left" else "1 0 0"
            ET.SubElement(joint, "axis", xyz=axis)
            lim = ET.SubElement(joint, "limit")
            lim.set("lower", _f(0.0))
            lim.set("upper", _f(max_flex))
            lim.set("effort", "12.0")
            lim.set("velocity", "6.0")
            dyn = ET.SubElement(joint, "dynamics")
            dyn.set("damping", "0.06")
            dyn.set("friction", "0.02")
            parent = link_name

            # Distal tip pad on the last link of each finger.
            if i == len(segs) - 1:
                ET.SubElement(
                    link, "visual",
                ).remove(link.find("visual")) if False else None
                _sphere_visual(link, f"{finger}_tip",
                               vec(0.0, length, 0.0), segs[-1][1] * 0.86, "joint")

    ET.indent(robot, space="  ")
    return ET.tostring(robot, encoding="unicode")


# --- geometry helpers -------------------------------------------------------
def _box_visual(link, name, center, rot, half, material) -> None:
    vis = ET.SubElement(link, "visual")
    vis.set("name", name)
    vis.append(_origin_xml(None, xyz=center, rot=rot))
    geo = ET.SubElement(vis, "geometry")
    ET.SubElement(geo, "box", size=" ".join(_f(2 * h) for h in np.asarray(half, float)))
    ET.SubElement(vis, "material", name=material)


def _box_inertial(link, name, center, rot, half, density) -> None:
    ext = np.asarray(half, float) * 2.0
    mass = density * float(np.prod(ext))
    inert = ET.SubElement(link, "inertial")
    inert.append(_origin_xml(None, xyz=center, rot=rot))
    ET.SubElement(inert, "mass", value=_f(mass))
    ixx = mass / 12.0 * (ext[1] ** 2 + ext[2] ** 2)
    iyy = mass / 12.0 * (ext[0] ** 2 + ext[2] ** 2)
    izz = mass / 12.0 * (ext[0] ** 2 + ext[1] ** 2)
    ET.SubElement(
        inert, "inertia",
        ixx=_f(ixx), ixy="0", ixz="0", iyy=_f(iyy), iyz="0", izz=_f(izz),
    )


def _cylinder_visual(link, name, p0, p1, r0, r1, material) -> None:
    """A cylinder spanning p0->p1, expressed in the link's local frame."""
    p0, p1 = vec(*p0), vec(*p1)
    axis = p1 - p0
    length = float(np.linalg.norm(axis))
    if length < 1e-9:
        return
    axis = axis / length
    # Rotation taking local +Y onto `axis` (bone convention), then rpy.
    from .math3d import rot_between

    rot = rot_between(vec(0.0, 1.0, 0.0), axis)
    vis = ET.SubElement(link, "visual")
    vis.set("name", name)
    vis.append(_origin_xml(None, xyz=(p0 + p1) * 0.5, rot=rot))
    geo = ET.SubElement(vis, "geometry")
    ET.SubElement(geo, "cylinder", radius=_f((r0 + r1) * 0.5), length=_f(length))
    ET.SubElement(vis, "material", name=material)


def _cylinder_inertial(link, name, length, radius, density) -> None:
    r = float(radius)
    mass = density * math.pi * r * r * float(length)
    ixx = mass / 12.0 * (3.0 * r * r + float(length) ** 2)
    iyy = mass / 12.0 * (3.0 * r * r + float(length) ** 2)
    izz = mass / 2.0 * r * r
    inert = ET.SubElement(link, "inertial")
    inert.append(_origin_xml(None, xyz=vec(0.0, length * 0.5, 0.0)))
    ET.SubElement(inert, "mass", value=_f(mass))
    ET.SubElement(
        inert, "inertia",
        ixx=_f(ixx), ixy="0", ixz="0", iyy=_f(iyy), iyz="0", izz=_f(izz),
    )


def _sphere_visual(link, name, center, radius, material) -> None:
    vis = ET.SubElement(link, "visual")
    vis.set("name", name)
    vis.append(_origin_xml(None, xyz=center))
    geo = ET.SubElement(vis, "geometry")
    ET.SubElement(geo, "sphere", radius=_f(radius))
    ET.SubElement(vis, "material", name=material)


def joint_table() -> list[tuple[str, float, float, float]]:
    """(joint name, lower, upper, default) for every actuated joint."""
    rows = []
    for finger in FINGERS:
        for i, suffix in enumerate(JOINT_SUFFIX):
            max_flex = FINGER_RIG[finger][2][i][2]
            rows.append((f"{finger}_{suffix}", 0.0, float(max_flex), 0.0))
    return rows
